# Generated by Django 5.0.6 on 2024-09-07 08:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="liked",
        ),
        migrations.AddField(
            model_name="rating",
            name="vote_type",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike")],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
