# Generated by Django 5.0.6 on 2024-09-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_game", "0002_remove_rating_liked_rating_vote_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="system_requirements",
        ),
        migrations.CreateModel(
            name="SystemRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        max_length=100, verbose_name="Операционная система"
                    ),
                ),
                ("cpu", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=50)),
                ("storage", models.CharField(max_length=50)),
                ("gpu", models.CharField(blank=True, max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_requirements",
                        to="shop_game.game",
                    ),
                ),
            ],
        ),
    ]
