# Generated by Django 5.0.6 on 2024-09-07 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_game", "0003_remove_game_system_requirements_systemrequirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemrequirement",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_requirements",
                to="shop_game.game",
                verbose_name="системные требования",
            ),
        ),
    ]
