# Generated by Django 5.0.6 on 2024-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_game", "0006_alter_supportticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="subject",
            field=models.CharField(blank=True, max_length=100, verbose_name="Тема"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name="Электронная почта пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="message",
            field=models.TextField(blank=True, verbose_name="Сообщение"),
        ),
    ]
